---
title: "Untitled"
author: "Carsten Behring"
date: "Tuesday, October 21, 2014"
output: html_document
---

```{r}
library(caret)
library(dplyr)
```


```{r cache=TRUE,echo=FALSE}

testing <- read.csv("./pml-testing.csv",stringsAsFactors=F) %>% select(-user_name,-cvtd_timestamp,-new_window)
testing <- as.data.frame(lapply(testing,as.numeric))


training <- read.csv("./pml-training.csv",stringsAsFactors=F,na.strings=c("NA",""))
training <- training %>% select(-user_name,-cvtd_timestamp,-new_window)
training <- training %>% mutate(classe=factor(training$classe))
classe <- training$classe;
training <- as.data.frame(lapply(training,as.numeric))
training$classe <- classe                                 



```

## Feature selection

I decided to use only the predictors with the raw sensor measurements and exclude therefore all others.
As they are summaries per time window, they should not add anything new to teh model.

```{r}
predictors_to_keep <- c("classe",grep("_x$|_y$|_z$",names(training),value = T))
training <- training[,predictors_to_keep]
testing <- testing[,predictors_to_keep[-1]]

```


```{r cache=TRUE}
training <- sample_n(training,100)
fit <- train(classe ~ .,data=training)
```

Confusion matrix:
```{r}
confusionMatrix(fit)
```

Prediction:
```{r}
predict(fit$finalModel,newdata=testing)
```





